### ISSUE TITLE
C / C++ compiler option warnings are showing during build

### ISSUE THREAD

**Issue by mikelangmayr** [CaltechOpticalObservatories/camera-interface-v1#21]
The following warning is showing:
- cc1plus: warning: command-line option ‘-std=c17’ is valid for C/ObjC but not for C++

Standard compiler version settings need to be separated between C and C++.

**Comment by astronomerdave** [comment]
What requires the use of `-std=c17` ?

**Comment by mikelangmayr** [comment]
@astronomerdave CI works without this flag so I'll remove it. I had an issue locally that it would default to c99 and break.
